# -*- coding: utf-8 -*-
"""Plagiarism_NLP_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXtIg_WHcjDidCk3EaLcJsvEagVoVFP_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/dataset.csv')
df.head()

df.drop(['Unnamed: 0'],axis=1,inplace=True)

df.head()

df['source_text'][0]

df['plagiarized_text'][0]

df['plagiarized_text'][267]

df.shape

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
import string

"""# **Text Cleaning**"""

def clean_text(text):
  text=text.translate(str.maketrans('','',string.punctuation))
  text=text.lower()
  stop_words=set(stopwords.words('english'))
  text=[word for word in text.split() if word not in stop_words]
  return " ".join(text)

clean_text("this is saqib khan @#$%;  what about you intelligent")

df["source_text"]=df["source_text"].apply(clean_text)
df["plagiarized_text"]=df["plagiarized_text"].apply(clean_text)
df["source_text"][0]

df['label'].value_counts()

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(df['source_text']+ " " + df['plagiarized_text'])

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,df['label'],test_size=0.2,random_state=42)

from sklearn.svm import SVC
svc=SVC(kernel='linear')
svc.fit(x_train,y_train)

svc.score(x_test,y_test)*100

from sklearn.metrics import accuracy_score
y_pred=svc.predict(x_test)
print("Accuracy =",accuracy_score(y_test,y_pred)*100)

"""# **App Making Streamlit**"""

import joblib

# Save the TF-IDF vectorizer
tfidf_path = "/content/tfidf.joblib"
joblib.dump(tfidf, tfidf_path)
print("✅ TF-IDF Vectorizer saved successfully!")


joblib.dump(svc, '/content/plagairize_NLP.joblib')

!pip install streamlit
!pip install pyngrok

!npm install localtunnel

# now make app.py in content at side of file

!streamlit run /content/app.py &> /content/logs.txt &

!npx localtunnel --port 8501